FROM node:20

WORKDIR /app

# Sao chép file package.json và package-lock.json, cài đặt dependencies
COPY package.json package-lock.json ./
RUN npm install

# Sao chép toàn bộ mã nguồn vào container
COPY . .

# Expose port mặc định của Vite Dev Server
EXPOSE 5173

# Chạy Vite Dev Server (npm run dev)
CMD ["npm", "run", "dev"]
