version: "3.8"

services:
  react-app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - my-network

  backend:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: "npm start"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
